### ISSUE TITLE
Decide on Vitest or Jest

### ISSUE THREAD

**Issue by HawaIbr01** [S3BzA/WhoseApp#10]
Waiting for feedback from SlothBot

**Comment by S3BzA** [comment]
Will do. Awaiting his reponse.

**Comment by S3BzA** [comment]
@HawaIbr01 I have been told Vitest is really good but you may make teh final decision as although we are working with Vite (for which Vitest is built) you may find jest better anyway.

**Comment by HawaIbr01** [comment]
Mhmmm I agree, I spoke to others as well, and I think I'd stick to jest, there's more sources out there for it!!

Thank you for getting back to me
